// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7jvdQemeVhQeLCrYcMBTUF
// Component: FDKX51wbLmrg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: 0joWdd7dF6TQ/component
import Select from "../../Select"; // plasmic-import: gUaVsqdTGH_a/component
import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7jvdQemeVhQeLCrYcMBTUF/projectcss
import sty from "./PlasmicOtpCodeForm.module.css"; // plasmic-import: FDKX51wbLmrg/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: uEBumg9MpBtc/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 4YWE9pC0XBhy/icon
import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon

createPlasmicElementProxy;

export type PlasmicOtpCodeForm__VariantMembers = {};
export type PlasmicOtpCodeForm__VariantsArgs = {};
type VariantPropType = keyof PlasmicOtpCodeForm__VariantsArgs;
export const PlasmicOtpCodeForm__VariantProps = new Array<VariantPropType>();

export type PlasmicOtpCodeForm__ArgsType = {
  cell?: string;
  nextStepTrigger?: (otp: string) => void;
};
type ArgPropType = keyof PlasmicOtpCodeForm__ArgsType;
export const PlasmicOtpCodeForm__ArgProps = new Array<ArgPropType>(
  "cell",
  "nextStepTrigger"
);

export type PlasmicOtpCodeForm__OverridesType = {
  root?: Flex__<"div">;
  otpInput?: Flex__<typeof TextInput>;
  select?: Flex__<typeof Select>;
  button?: Flex__<typeof Button>;
};

export interface DefaultOtpCodeFormProps {
  cell?: string;
  nextStepTrigger?: (otp: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOtpCodeForm__RenderFunc(props: {
  variants: PlasmicOtpCodeForm__VariantsArgs;
  args: PlasmicOtpCodeForm__ArgsType;
  overrides: PlasmicOtpCodeForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "otpInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "25"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__ef1Ml)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zwor6
          )}
        >
          {
            "\u06a9\u062f\u062a\u0627\u06cc\u06cc\u062f \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f."
          }
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___6J1Rc
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return `کد تایید به شماره موبایل ${$props.cell} ارسال شد.`;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "\u06a9\u062f \u062a\u0627\u06cc\u06cc\u062f \u0628\u0647 \u0634\u0645\u0627\u0631\u0647 \u0645\u0648\u0628\u0627\u06cc\u0644 x \u0627\u0631\u0633\u0627\u0644 \u0634\u062f.";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__iWt9G)}
      >
        <TextInput
          data-plasmic-name={"otpInput"}
          data-plasmic-override={overrides.otpInput}
          className={classNames("__wab_instance", sty.otpInput)}
          onChange={(...eventArgs) => {
            generateStateOnChangeProp($state, ["otpInput", "value"])(
              (e => e.target?.value).apply(null, eventArgs)
            );
          }}
          placeholder={``}
          type={"tel"}
          value={generateStateValueProp($state, ["otpInput", "value"]) ?? ""}
        />

        {(() => {
          try {
            return $ctx.Growthbook.features["aaa:enable-oauth-login"];
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return false;
            }
            throw e;
          }
        })() ? (
          <Select
            data-plasmic-name={"select"}
            data-plasmic-override={overrides.select}
            className={classNames("__wab_instance", sty.select)}
            onChange={(...eventArgs) => {
              generateStateOnChangeProp($state, ["select", "value"])(
                eventArgs[0]
              );
            }}
            options={(() => {
              const __composite = [
                { value: null, label: null },
                { value: null, label: null }
              ];
              __composite["0"]["value"] = "25";
              __composite["0"]["label"] = "+98";
              __composite["1"]["value"] = "12";
              __composite["1"]["label"] = "+1";
              return __composite;
            })()}
            value={generateStateValueProp($state, ["select", "value"])}
          />
        ) : null}
      </Stack__>
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        children2={"\u0648\u0631\u0648\u062f"}
        className={classNames("__wab_instance", sty.button)}
        onClick={async event => {
          const $steps = {};

          $steps["updateCellInputValue"] =
            $state.otpInput.value.length < 4
              ? (() => {
                  const actionArgs = {
                    args: [
                      "error",
                      "\u06a9\u062f\u062a\u0627\u06cc\u06cc\u062f \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f."
                    ]
                  };
                  return $globalActions["Fragment.showToast"]?.apply(null, [
                    ...actionArgs.args
                  ]);
                })()
              : undefined;
          if (
            $steps["updateCellInputValue"] != null &&
            typeof $steps["updateCellInputValue"] === "object" &&
            typeof $steps["updateCellInputValue"].then === "function"
          ) {
            $steps["updateCellInputValue"] = await $steps[
              "updateCellInputValue"
            ];
          }

          $steps["runNextStepTrigger"] = true
            ? (() => {
                const actionArgs = {
                  eventRef: $props["nextStepTrigger"],
                  args: [
                    (() => {
                      try {
                        return $state.otpInput.value;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()
                  ]
                };
                return (({ eventRef, args }) => {
                  return eventRef?.(...(args ?? []));
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["runNextStepTrigger"] != null &&
            typeof $steps["runNextStepTrigger"] === "object" &&
            typeof $steps["runNextStepTrigger"].then === "function"
          ) {
            $steps["runNextStepTrigger"] = await $steps["runNextStepTrigger"];
          }
        }}
      />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "otpInput", "select", "button"],
  otpInput: ["otpInput"],
  select: ["select"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  otpInput: typeof TextInput;
  select: typeof Select;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOtpCodeForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOtpCodeForm__VariantsArgs;
    args?: PlasmicOtpCodeForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOtpCodeForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOtpCodeForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOtpCodeForm__ArgProps,
          internalVariantPropNames: PlasmicOtpCodeForm__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOtpCodeForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOtpCodeForm";
  } else {
    func.displayName = `PlasmicOtpCodeForm.${nodeName}`;
  }
  return func;
}

export const PlasmicOtpCodeForm = Object.assign(
  // Top-level PlasmicOtpCodeForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    otpInput: makeNodeComponent("otpInput"),
    select: makeNodeComponent("select"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicOtpCodeForm
    internalVariantProps: PlasmicOtpCodeForm__VariantProps,
    internalArgProps: PlasmicOtpCodeForm__ArgProps
  }
);

export default PlasmicOtpCodeForm;
/* prettier-ignore-end */
